name: Publish

on:
  push:
    branches: main

jobs:
  siege:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build_master
        uses: docker/build-push-action@v2
        with:
          file: ./siege/Dockerfile
          push: true
          tags: ghcr.io/snorwin/siege:4.1.2
          platforms: linux/amd64